solr_entity=http://entity-api.eanadev.org:9191/solr/production

#download data for that period from Google Analytics - format YYYY-MM-DD
start_date=2021-01-01
end_date=2021-04-30 

#total number of queries as output
sample_size=400

#sampling made by Google Analytics when downloading the data. Options: SMALL, LARGE and DEFAULT
ga_sampling=LARGE

#Google Analytics credentials
gakey=/home/mmarrero/eclipse-workspace/client_secrets.json

